server:
  port: 8082

spring:
  kafka:
    topic:
      name: transaction
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}

websocket.topic: topic

management:
  endpoints:
    web:
      exposure:
        include: info, health

info:
  application:
    version: '@project.version@'
