version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - 22181:2181
    networks:
      - kafka-net

  kafka-server:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://kafka-server:29092
    networks:
      - kafka-net

  producer-service:
    image: 'producer-service'
    ports:
      - 8081:8081
    depends_on:
      - kafka-server
    environment:
      KAFKA_SERVERS: kafka-server:29092
    networks:
      - kafka-net

  consumer-service:
    image: "consumer-service"
    ports:
      - 8082:8082
    depends_on:
      - kafka-server
    environment:
      KAFKA_SERVERS: kafka-server:29092
    networks:
      - kafka-net

  web-socket:
    image: "web-socket"
    ports:
      - 8083:8080
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka-server:29092
    depends_on:
      - kafka-server
    networks:
      - kafka-net